import type {
  AIMessage,
  AIUsage,
} from "../ai/providers/ai-provider.interface.js";

/**
 * Lifecycle statuses for agent execution.
 */
export const AGENT_STATUSES = {
  IDLE: "IDLE",
  RUNNING: "RUNNING",
  PAUSED: "PAUSED",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
} as const;

export type AgentStatus =
  (typeof AGENT_STATUSES)[keyof typeof AGENT_STATUSES];

/**
 * Status of an individual tool call during agent execution.
 */
export const TOOL_CALL_STATUSES = {
  PENDING: "PENDING",
  EXECUTING: "EXECUTING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
} as const;

export type ToolCallStatus =
  (typeof TOOL_CALL_STATUSES)[keyof typeof TOOL_CALL_STATUSES];

/**
 * Representation of a tool call request generated by the model.
 */
export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

/**
 * Representation of the outcome of a tool execution.
 */
export interface ToolCallResult {
  toolCallId: string;
  toolName: string;
  output: unknown;
  isError?: boolean | undefined;
  error?: string | undefined;
  durationMs?: number | undefined;
}

/**
 * Comprehensive tracking information for a tool call lifecycle.
 */
export interface ToolCallInfo {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
  status: ToolCallStatus;
  result?: unknown | undefined;
  error?: string | undefined;
  startedAt?: Date | undefined;
  completedAt?: Date | undefined;
  durationMs?: number | undefined;
}

/**
 * Input parameters required to initiate an agent execution.
 */
export interface AgentExecutionInput {
  userId: string;
  task: string;
  conversationId?: string | undefined;
  systemPrompt?: string | undefined;
  maxSteps?: number | undefined;
  context?: Record<string, unknown> | undefined;
  metadata?: Record<string, unknown> | undefined;
  initialMessages?: AIMessage[] | undefined;
}

/**
 * Active runtime state of an ongoing or persisted agent execution.
 */
export interface AgentExecutionState {
  id: string;
  userId: string;
  task: string;
  status: AgentStatus;
  currentStep: number;
  maxSteps: number;
  messages: AIMessage[];
  toolCalls: ToolCallInfo[];
  usage: AIUsage;
  conversationId?: string | undefined;
  output?: string | undefined;
  error?: string | undefined;
  startedAt: Date;
  updatedAt: Date;
  completedAt?: Date | undefined;
  metadata?: Record<string, unknown> | undefined;
}

/**
 * Final summarized result returned upon completion of agent execution.
 */
export interface AgentExecutionResult {
  executionId: string;
  userId: string;
  task: string;
  status: AgentStatus;
  output: string | null;
  stepsCompleted: number;
  toolCalls: ToolCallInfo[];
  usage: AIUsage;
  startedAt: Date;
  completedAt: Date;
  durationMs: number;
  conversationId?: string | undefined;
  error?: string | undefined;
  metadata?: Record<string, unknown> | undefined;
}

/**
 * Safe high-level tool execution status event for client streaming.
 */
export interface ToolStatusEvent {
  status: "running" | "completed" | "failed";
  tool: string;
  toolCallId?: string | undefined;
  error?: string | undefined;
  durationMs?: number | undefined;
}

/**
 * Event callbacks for agent progressive streaming and lifecycle tracking.
 */
export interface AgentStreamCallbacks {
  onStart?: (data: {
    userMessage?: Record<string, unknown> | undefined;
    conversationId?: string | undefined;
  }) => void;
  onStatus?: (status: string, message: string) => void;
  onToolStatus?: (event: ToolStatusEvent) => void;
  onChunk?: (chunk: string) => void;
  onDone?: (result: AgentExecutionResult) => void;
  onError?: (error: unknown) => void;
}

/**
 * Execution options for AgentLoop and AgentService.
 */
export interface AgentRunOptions {
  callbacks?: AgentStreamCallbacks | undefined;
  signal?: AbortSignal | undefined;
}
